name: Flake

on: pull_request

permissions:
  id-token: "write"
  contents: "read"
  issues: "write"

jobs:
  lockfile-drv-changed:
    runs-on: ubuntu-24.04

    steps:
      - name: Check changed files
        id: changed
        run: |
          files=$(gh pr diff "$PR_NUMBER" --name-only)
          if [ "$files" = "flake.lock" ]; then
            echo "only_lock_changed=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "only_lock_changed=false" | tee -a "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: steps.changed.outputs.only_lock_changed == 'true'
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Install nix-flake-diff-packages
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          nix profile install github:josh/nixbits#nix-flake-diff-packages

      - name: Compare head and base flake packages
        id: diff
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          nix-flake-diff-packages --changes "$BASE_FLAKE" "$HEAD_FLAKE"
        env:
          BASE_FLAKE: "github:${{ github.event.pull_request.base.repo.full_name }}/${{ github.event.pull_request.base.sha }}"
          HEAD_FLAKE: "github:${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.sha }}"

      - name: Add noop label
        if: failure() && steps.diff.outcome == 'failure' && steps.changed.outputs.only_lock_changed == 'true'
        run: gh pr edit "$PR_NUMBER" --add-label "noop"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Remove noop label
        if: success() && steps.changed.outputs.only_lock_changed == 'true'
        run: gh pr edit "$PR_NUMBER" --remove-label "noop" || true
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
